const driversCopy = {
  ru: {
    eyebrow: 'Транспортным компаниям', title: 'Станьте перевозчиком Riderra',
    lead: 'Получайте заказы на аэропортовые и городские трансферы от Riderra и наших партнёров. Вы сами указываете географию, автопарк и нетто-тарифы.',
    startButton: 'Заполнить заявку', loginButton: 'Войти в кабинет', processTitle: 'Как начать работу',
    steps: [
      { title: 'Расскажите о компании', text: 'Контакты и регионы работы.' },
      { title: 'Предложите тарифы', text: 'Фиксированные маршруты или цена за километр.' },
      { title: 'Согласуем условия', text: 'Проверим данные и свяжемся с вами.' }
    ],
    applicationEyebrow: 'Заявка перевозчика', applicationTitle: 'Один шаг до знакомства',
    applicationText: 'Заполните только то, что уже известно. Тарифы можно уточнить вместе с менеджером после заявки.',
    wikiButton: 'Правила работы с Riderra', alreadyRegistered: 'Уже зарегистрированы? Войти',
    successEyebrow: 'Заявка отправлена', successTitle: 'Спасибо за интерес к Riderra',
    companySection: 'Компания и контакты', requiredNote: 'Поля со звёздочкой обязательны.',
    name: 'Название компании / ваше имя *', email: 'Рабочий email *', phone: 'Телефон или WhatsApp *',
    city: 'Города и регионы работы *', cityHelp: 'Например: Los Angeles, Orange County, LAX.',
    ratesSection: 'Нетто-тарифы', ratesHelp: 'Можно указать фиксированные маршруты, ставку за километр или оба варианта.',
    fixedRatesTitle: 'Фиксированные маршруты', fixedRatesHelp: 'Цена перевозчика за трансфер в одну сторону.',
    fixedFrom: 'Откуда', fixedTo: 'Куда', fixedPrice: 'Цена', fixedCurrency: 'Валюта',
    fromPlaceholder: 'LAX Airport', toPlaceholder: 'Downtown LA', addRoute: 'Добавить маршрут', removeRoute: 'Удалить маршрут',
    routesPerKm: 'Ставка за километр', perKmPlaceholder: 'Например, 1.20 EUR/km', perKmHelp: 'Если работаете только по фиксированным ценам, оставьте поле пустым.',
    detailsSection: 'Автопарк и условия', detailsHelp: 'Эти данные помогут быстрее проверить заявку.',
    comment: 'Комментарий', commentPlaceholder: 'Количество и классы машин, вместимость, лицензии, аэропортовые разрешения, условия ожидания и другие важные детали.',
    submit: 'Отправить заявку', submitting: 'Отправляем…', consent: 'Отправляя заявку, вы разрешаете Riderra связаться с вами по вопросам сотрудничества.',
    note: 'Мы получили ваши данные и свяжемся с вами, чтобы проверить географию, автомобили и тарифы.',
    error: 'Не удалось отправить заявку. Проверьте данные и попробуйте ещё раз.'
  },
  en: {
    eyebrow: 'For transport companies', title: 'Become a Riderra fleet partner',
    lead: 'Receive airport and city transfer requests from Riderra and our partners. You choose your service area, fleet and net rates.',
    startButton: 'Complete the application', loginButton: 'Partner login', processTitle: 'How to get started',
    steps: [
      { title: 'Tell us about your company', text: 'Contacts and operating regions.' },
      { title: 'Share your rates', text: 'Fixed routes or a per-kilometre rate.' },
      { title: 'Agree the terms', text: 'We review the details and contact you.' }
    ],
    applicationEyebrow: 'Fleet partner application', applicationTitle: 'Let’s get acquainted',
    applicationText: 'Share what you already know. Rates can be clarified with a manager after you apply.',
    wikiButton: 'How working with Riderra works', alreadyRegistered: 'Already registered? Log in',
    successEyebrow: 'Application sent', successTitle: 'Thank you for your interest in Riderra',
    companySection: 'Company and contact details', requiredNote: 'Fields marked with an asterisk are required.',
    name: 'Company name / your name *', email: 'Business email *', phone: 'Phone or WhatsApp *',
    city: 'Cities and operating regions *', cityHelp: 'For example: Los Angeles, Orange County, LAX.',
    ratesSection: 'Your net rates', ratesHelp: 'Add fixed routes, a per-kilometre rate, or both.',
    fixedRatesTitle: 'Fixed routes', fixedRatesHelp: 'Your one-way net transfer price.',
    fixedFrom: 'From', fixedTo: 'To', fixedPrice: 'Price', fixedCurrency: 'Currency',
    fromPlaceholder: 'LAX Airport', toPlaceholder: 'Downtown LA', addRoute: 'Add another route', removeRoute: 'Remove route',
    routesPerKm: 'Rate per kilometre', perKmPlaceholder: 'For example, 1.20 EUR/km', perKmHelp: 'Leave this blank if you only use fixed prices.',
    detailsSection: 'Fleet and operating terms', detailsHelp: 'This information helps us review your application faster.',
    comment: 'Additional information', commentPlaceholder: 'Fleet size, vehicle classes and capacity, licences, airport permits, waiting terms and anything else we should know.',
    submit: 'Send application', submitting: 'Sending…', consent: 'By submitting, you allow Riderra to contact you about a potential partnership.',
    note: 'We have received your details and will contact you to review your coverage, vehicles and rates.',
    error: 'We could not send the application. Please check the details and try again.'
  },
  de: {
    eyebrow: 'Für Transportunternehmen', title: 'Werden Sie Riderra-Flottenpartner',
    lead: 'Erhalten Sie Anfragen für Flughafen- und Stadttransfers von Riderra und unseren Partnern. Sie bestimmen Einsatzgebiet, Fuhrpark und Nettotarife.',
    startButton: 'Bewerbung ausfüllen', loginButton: 'Partner-Login', processTitle: 'So starten Sie',
    steps: [
      { title: 'Stellen Sie Ihr Unternehmen vor', text: 'Kontaktdaten und Einsatzgebiete.' },
      { title: 'Teilen Sie Ihre Tarife mit', text: 'Festpreise oder Preis pro Kilometer.' },
      { title: 'Bedingungen vereinbaren', text: 'Wir prüfen die Angaben und melden uns.' }
    ],
    applicationEyebrow: 'Bewerbung als Flottenpartner', applicationTitle: 'Lernen wir uns kennen',
    applicationText: 'Teilen Sie uns mit, was bereits feststeht. Tarife können Sie nach der Bewerbung mit unserem Team abstimmen.',
    wikiButton: 'Zusammenarbeit mit Riderra', alreadyRegistered: 'Bereits registriert? Anmelden',
    successEyebrow: 'Bewerbung gesendet', successTitle: 'Vielen Dank für Ihr Interesse an Riderra',
    companySection: 'Unternehmen und Kontaktdaten', requiredNote: 'Mit Sternchen markierte Felder sind Pflichtfelder.',
    name: 'Firmenname / Ihr Name *', email: 'Geschäftliche E-Mail *', phone: 'Telefon oder WhatsApp *',
    city: 'Städte und Einsatzgebiete *', cityHelp: 'Zum Beispiel: Los Angeles, Orange County, LAX.',
    ratesSection: 'Ihre Nettotarife', ratesHelp: 'Geben Sie Festpreise, einen Kilometerpreis oder beides an.',
    fixedRatesTitle: 'Feste Routen', fixedRatesHelp: 'Ihr Nettopreis für einen Transfer in eine Richtung.',
    fixedFrom: 'Von', fixedTo: 'Nach', fixedPrice: 'Preis', fixedCurrency: 'Währung',
    fromPlaceholder: 'Flughafen LAX', toPlaceholder: 'Downtown LA', addRoute: 'Weitere Route hinzufügen', removeRoute: 'Route entfernen',
    routesPerKm: 'Preis pro Kilometer', perKmPlaceholder: 'Zum Beispiel 1,20 EUR/km', perKmHelp: 'Leer lassen, wenn Sie nur mit Festpreisen arbeiten.',
    detailsSection: 'Fuhrpark und Bedingungen', detailsHelp: 'Diese Angaben helfen uns, Ihre Bewerbung schneller zu prüfen.',
    comment: 'Zusätzliche Angaben', commentPlaceholder: 'Fuhrparkgröße, Fahrzeugklassen und Kapazität, Lizenzen, Flughafengenehmigungen, Wartebedingungen und weitere wichtige Angaben.',
    submit: 'Bewerbung senden', submitting: 'Wird gesendet…', consent: 'Mit dem Absenden erlauben Sie Riderra, Sie zu einer möglichen Partnerschaft zu kontaktieren.',
    note: 'Wir haben Ihre Angaben erhalten und melden uns zur Abstimmung von Einsatzgebiet, Fahrzeugen und Tarifen.',
    error: 'Die Bewerbung konnte nicht gesendet werden. Bitte prüfen Sie Ihre Angaben und versuchen Sie es erneut.'
  },
  es: {
    eyebrow: 'Para empresas de transporte', title: 'Conviértete en proveedor de flota de Riderra',
    lead: 'Recibe solicitudes de traslados urbanos y de aeropuerto de Riderra y nuestros socios. Tú eliges la zona de servicio, la flota y las tarifas netas.',
    startButton: 'Completar la solicitud', loginButton: 'Acceso para socios', processTitle: 'Cómo empezar',
    steps: [
      { title: 'Cuéntanos sobre tu empresa', text: 'Contactos y zonas de operación.' },
      { title: 'Comparte tus tarifas', text: 'Rutas fijas o tarifa por kilómetro.' },
      { title: 'Acordamos las condiciones', text: 'Revisamos los datos y te contactamos.' }
    ],
    applicationEyebrow: 'Solicitud de proveedor', applicationTitle: 'Conozcámonos',
    applicationText: 'Comparte lo que ya sabes. Podrás concretar las tarifas con un responsable después de enviar la solicitud.',
    wikiButton: 'Cómo trabajar con Riderra', alreadyRegistered: '¿Ya estás registrado? Inicia sesión',
    successEyebrow: 'Solicitud enviada', successTitle: 'Gracias por tu interés en Riderra',
    companySection: 'Empresa y datos de contacto', requiredNote: 'Los campos con asterisco son obligatorios.',
    name: 'Nombre de la empresa / tu nombre *', email: 'Correo de empresa *', phone: 'Teléfono o WhatsApp *',
    city: 'Ciudades y zonas de operación *', cityHelp: 'Por ejemplo: Los Angeles, Orange County, LAX.',
    ratesSection: 'Tus tarifas netas', ratesHelp: 'Añade rutas fijas, una tarifa por kilómetro o ambas.',
    fixedRatesTitle: 'Rutas fijas', fixedRatesHelp: 'Tu precio neto por traslado de ida.',
    fixedFrom: 'Origen', fixedTo: 'Destino', fixedPrice: 'Precio', fixedCurrency: 'Moneda',
    fromPlaceholder: 'Aeropuerto LAX', toPlaceholder: 'Downtown LA', addRoute: 'Añadir otra ruta', removeRoute: 'Eliminar ruta',
    routesPerKm: 'Tarifa por kilómetro', perKmPlaceholder: 'Por ejemplo, 1,20 EUR/km', perKmHelp: 'Déjalo vacío si solo trabajas con precios fijos.',
    detailsSection: 'Flota y condiciones', detailsHelp: 'Esta información nos ayuda a revisar tu solicitud más rápido.',
    comment: 'Información adicional', commentPlaceholder: 'Tamaño de la flota, clases y capacidad, licencias, permisos de aeropuerto, condiciones de espera y otros datos importantes.',
    submit: 'Enviar solicitud', submitting: 'Enviando…', consent: 'Al enviar la solicitud, autorizas a Riderra a contactarte sobre una posible colaboración.',
    note: 'Hemos recibido tus datos y te contactaremos para revisar cobertura, vehículos y tarifas.',
    error: 'No pudimos enviar la solicitud. Revisa los datos e inténtalo de nuevo.'
  },
  fr: {
    eyebrow: 'Pour les sociétés de transport', title: 'Devenez partenaire flotte de Riderra',
    lead: 'Recevez des demandes de transferts aéroport et ville de Riderra et de nos partenaires. Vous choisissez votre zone, votre flotte et vos tarifs nets.',
    startButton: 'Remplir la candidature', loginButton: 'Connexion partenaire', processTitle: 'Comment commencer',
    steps: [
      { title: 'Présentez votre entreprise', text: 'Coordonnées et zones d’activité.' },
      { title: 'Partagez vos tarifs', text: 'Trajets fixes ou tarif au kilomètre.' },
      { title: 'Convenons des conditions', text: 'Nous vérifions les informations et vous contactons.' }
    ],
    applicationEyebrow: 'Candidature partenaire flotte', applicationTitle: 'Faisons connaissance',
    applicationText: 'Indiquez ce que vous savez déjà. Les tarifs pourront être précisés avec un responsable après votre candidature.',
    wikiButton: 'Travailler avec Riderra', alreadyRegistered: 'Déjà inscrit ? Se connecter',
    successEyebrow: 'Candidature envoyée', successTitle: 'Merci de votre intérêt pour Riderra',
    companySection: 'Entreprise et coordonnées', requiredNote: 'Les champs marqués d’un astérisque sont obligatoires.',
    name: 'Nom de l’entreprise / votre nom *', email: 'E-mail professionnel *', phone: 'Téléphone ou WhatsApp *',
    city: 'Villes et zones d’activité *', cityHelp: 'Par exemple : Los Angeles, Orange County, LAX.',
    ratesSection: 'Vos tarifs nets', ratesHelp: 'Ajoutez des trajets fixes, un tarif au kilomètre ou les deux.',
    fixedRatesTitle: 'Trajets fixes', fixedRatesHelp: 'Votre tarif net pour un aller simple.',
    fixedFrom: 'Départ', fixedTo: 'Arrivée', fixedPrice: 'Prix', fixedCurrency: 'Devise',
    fromPlaceholder: 'Aéroport LAX', toPlaceholder: 'Downtown LA', addRoute: 'Ajouter un trajet', removeRoute: 'Supprimer le trajet',
    routesPerKm: 'Tarif au kilomètre', perKmPlaceholder: 'Par exemple, 1,20 EUR/km', perKmHelp: 'Laissez vide si vous utilisez uniquement des prix fixes.',
    detailsSection: 'Flotte et conditions', detailsHelp: 'Ces informations nous aident à examiner votre candidature plus rapidement.',
    comment: 'Informations complémentaires', commentPlaceholder: 'Taille de la flotte, catégories et capacité, licences, autorisations aéroportuaires, conditions d’attente et autres informations utiles.',
    submit: 'Envoyer la candidature', submitting: 'Envoi…', consent: 'En envoyant ce formulaire, vous autorisez Riderra à vous contacter au sujet d’un partenariat potentiel.',
    note: 'Nous avons reçu vos informations et vous contacterons pour examiner votre couverture, vos véhicules et vos tarifs.',
    error: 'La candidature n’a pas pu être envoyée. Vérifiez les informations et réessayez.'
  },
  el: {
    eyebrow: 'Για εταιρείες μεταφορών', title: 'Γίνετε συνεργάτης στόλου της Riderra',
    lead: 'Λάβετε αιτήματα για μεταφορές αεροδρομίου και πόλης από τη Riderra και τους συνεργάτες μας. Εσείς επιλέγετε περιοχή, στόλο και καθαρές τιμές.',
    startButton: 'Συμπλήρωση αίτησης', loginButton: 'Σύνδεση συνεργάτη', processTitle: 'Πώς να ξεκινήσετε',
    steps: [
      { title: 'Παρουσιάστε την εταιρεία σας', text: 'Στοιχεία επικοινωνίας και περιοχές λειτουργίας.' },
      { title: 'Μοιραστείτε τις τιμές σας', text: 'Σταθερές διαδρομές ή τιμή ανά χιλιόμετρο.' },
      { title: 'Συμφωνήστε τους όρους', text: 'Ελέγχουμε τα στοιχεία και επικοινωνούμε μαζί σας.' }
    ],
    applicationEyebrow: 'Αίτηση συνεργάτη στόλου', applicationTitle: 'Ας γνωριστούμε',
    applicationText: 'Συμπληρώστε όσα γνωρίζετε ήδη. Οι τιμές μπορούν να διευκρινιστούν με υπεύθυνο μετά την αίτηση.',
    wikiButton: 'Συνεργασία με τη Riderra', alreadyRegistered: 'Έχετε ήδη εγγραφεί; Συνδεθείτε',
    successEyebrow: 'Η αίτηση στάλθηκε', successTitle: 'Ευχαριστούμε για το ενδιαφέρον σας για τη Riderra',
    companySection: 'Εταιρεία και στοιχεία επικοινωνίας', requiredNote: 'Τα πεδία με αστερίσκο είναι υποχρεωτικά.',
    name: 'Επωνυμία εταιρείας / όνομά σας *', email: 'Επαγγελματικό email *', phone: 'Τηλέφωνο ή WhatsApp *',
    city: 'Πόλεις και περιοχές λειτουργίας *', cityHelp: 'Για παράδειγμα: Los Angeles, Orange County, LAX.',
    ratesSection: 'Καθαρές τιμές', ratesHelp: 'Προσθέστε σταθερές διαδρομές, τιμή ανά χιλιόμετρο ή και τα δύο.',
    fixedRatesTitle: 'Σταθερές διαδρομές', fixedRatesHelp: 'Η καθαρή τιμή σας για μονή διαδρομή.',
    fixedFrom: 'Από', fixedTo: 'Προς', fixedPrice: 'Τιμή', fixedCurrency: 'Νόμισμα',
    fromPlaceholder: 'Αεροδρόμιο LAX', toPlaceholder: 'Downtown LA', addRoute: 'Προσθήκη διαδρομής', removeRoute: 'Αφαίρεση διαδρομής',
    routesPerKm: 'Τιμή ανά χιλιόμετρο', perKmPlaceholder: 'Για παράδειγμα, 1,20 EUR/km', perKmHelp: 'Αφήστε το κενό αν χρησιμοποιείτε μόνο σταθερές τιμές.',
    detailsSection: 'Στόλος και όροι', detailsHelp: 'Αυτές οι πληροφορίες βοηθούν να εξετάσουμε γρηγορότερα την αίτησή σας.',
    comment: 'Πρόσθετες πληροφορίες', commentPlaceholder: 'Μέγεθος στόλου, κατηγορίες και χωρητικότητα οχημάτων, άδειες, άδειες αεροδρομίου, όροι αναμονής και άλλες πληροφορίες.',
    submit: 'Αποστολή αίτησης', submitting: 'Αποστολή…', consent: 'Με την υποβολή επιτρέπετε στη Riderra να επικοινωνήσει μαζί σας για πιθανή συνεργασία.',
    note: 'Λάβαμε τα στοιχεία σας και θα επικοινωνήσουμε για περιοχές, οχήματα και τιμές.',
    error: 'Η αίτηση δεν στάλθηκε. Ελέγξτε τα στοιχεία και δοκιμάστε ξανά.'
  },
  th: {
    eyebrow: 'สำหรับบริษัทขนส่ง', title: 'ร่วมเป็นพันธมิตรผู้ให้บริการรถกับ Riderra',
    lead: 'รับคำขอบริการรับส่งสนามบินและในเมืองจาก Riderra และพันธมิตรของเรา คุณกำหนดพื้นที่ให้บริการ รถ และราคาสุทธิได้เอง',
    startButton: 'กรอกใบสมัคร', loginButton: 'เข้าสู่ระบบพันธมิตร', processTitle: 'วิธีเริ่มต้น',
    steps: [
      { title: 'แนะนำบริษัทของคุณ', text: 'ข้อมูลติดต่อและพื้นที่ให้บริการ' },
      { title: 'แจ้งราคาของคุณ', text: 'เส้นทางราคาคงที่หรือราคาต่อกิโลเมตร' },
      { title: 'ตกลงเงื่อนไข', text: 'เราตรวจสอบข้อมูลและติดต่อคุณ' }
    ],
    applicationEyebrow: 'ใบสมัครพันธมิตรผู้ให้บริการรถ', applicationTitle: 'มาทำความรู้จักกัน',
    applicationText: 'กรอกข้อมูลที่ทราบก่อน โดยสามารถตกลงรายละเอียดราคากับผู้จัดการได้หลังส่งใบสมัคร',
    wikiButton: 'วิธีทำงานกับ Riderra', alreadyRegistered: 'ลงทะเบียนแล้ว? เข้าสู่ระบบ',
    successEyebrow: 'ส่งใบสมัครแล้ว', successTitle: 'ขอบคุณที่สนใจ Riderra',
    companySection: 'บริษัทและข้อมูลติดต่อ', requiredNote: 'ช่องที่มีเครื่องหมายดอกจันจำเป็นต้องกรอก',
    name: 'ชื่อบริษัท / ชื่อของคุณ *', email: 'อีเมลธุรกิจ *', phone: 'โทรศัพท์หรือ WhatsApp *',
    city: 'เมืองและพื้นที่ให้บริการ *', cityHelp: 'ตัวอย่าง: Los Angeles, Orange County, LAX',
    ratesSection: 'ราคาสุทธิของคุณ', ratesHelp: 'เพิ่มเส้นทางราคาคงที่ ราคาต่อกิโลเมตร หรือทั้งสองแบบ',
    fixedRatesTitle: 'เส้นทางราคาคงที่', fixedRatesHelp: 'ราคาสุทธิของคุณสำหรับเที่ยวเดียว',
    fixedFrom: 'จาก', fixedTo: 'ไป', fixedPrice: 'ราคา', fixedCurrency: 'สกุลเงิน',
    fromPlaceholder: 'สนามบิน LAX', toPlaceholder: 'Downtown LA', addRoute: 'เพิ่มเส้นทาง', removeRoute: 'ลบเส้นทาง',
    routesPerKm: 'ราคาต่อกิโลเมตร', perKmPlaceholder: 'ตัวอย่าง 1.20 EUR/km', perKmHelp: 'เว้นว่างหากใช้เฉพาะราคาคงที่',
    detailsSection: 'รถและเงื่อนไขการให้บริการ', detailsHelp: 'ข้อมูลนี้ช่วยให้เราตรวจสอบใบสมัครได้เร็วขึ้น',
    comment: 'ข้อมูลเพิ่มเติม', commentPlaceholder: 'จำนวนรถ ประเภทรถและความจุ ใบอนุญาต ใบอนุญาตสนามบิน เงื่อนไขการรอ และข้อมูลสำคัญอื่น ๆ',
    submit: 'ส่งใบสมัคร', submitting: 'กำลังส่ง…', consent: 'เมื่อส่งใบสมัคร คุณอนุญาตให้ Riderra ติดต่อเกี่ยวกับความร่วมมือที่อาจเกิดขึ้น',
    note: 'เราได้รับข้อมูลแล้วและจะติดต่อเพื่อตรวจสอบพื้นที่ รถ และราคา',
    error: 'ไม่สามารถส่งใบสมัครได้ โปรดตรวจสอบข้อมูลแล้วลองอีกครั้ง'
  },
  ar: {
    eyebrow: 'لشركات النقل', title: 'انضم إلى Riderra كشريك أسطول',
    lead: 'استقبل طلبات نقل من المطارات وداخل المدن من Riderra وشركائنا. أنت تحدد منطقة الخدمة والأسطول والأسعار الصافية.',
    startButton: 'أكمل الطلب', loginButton: 'دخول الشركاء', processTitle: 'كيفية البدء',
    steps: [
      { title: 'عرّفنا بشركتك', text: 'بيانات الاتصال ومناطق العمل.' },
      { title: 'شارك أسعارك', text: 'مسارات ثابتة أو سعر لكل كيلومتر.' },
      { title: 'نتفق على الشروط', text: 'نراجع البيانات ونتواصل معك.' }
    ],
    applicationEyebrow: 'طلب شريك أسطول', applicationTitle: 'لنتعرف إلى بعضنا',
    applicationText: 'أرسل ما تعرفه الآن، ويمكن توضيح الأسعار مع مدير بعد تقديم الطلب.',
    wikiButton: 'كيفية العمل مع Riderra', alreadyRegistered: 'مسجل بالفعل؟ تسجيل الدخول',
    successEyebrow: 'تم إرسال الطلب', successTitle: 'شكرًا لاهتمامك بـ Riderra',
    companySection: 'الشركة وبيانات الاتصال', requiredNote: 'الحقول المميزة بنجمة مطلوبة.',
    name: 'اسم الشركة / اسمك *', email: 'البريد الإلكتروني للعمل *', phone: 'الهاتف أو WhatsApp *',
    city: 'المدن ومناطق العمل *', cityHelp: 'مثال: Los Angeles, Orange County, LAX.',
    ratesSection: 'أسعارك الصافية', ratesHelp: 'أضف مسارات ثابتة أو سعرًا لكل كيلومتر أو كليهما.',
    fixedRatesTitle: 'المسارات الثابتة', fixedRatesHelp: 'سعرك الصافي للنقل باتجاه واحد.',
    fixedFrom: 'من', fixedTo: 'إلى', fixedPrice: 'السعر', fixedCurrency: 'العملة',
    fromPlaceholder: 'مطار LAX', toPlaceholder: 'Downtown LA', addRoute: 'إضافة مسار', removeRoute: 'حذف المسار',
    routesPerKm: 'السعر لكل كيلومتر', perKmPlaceholder: 'مثال: 1.20 EUR/km', perKmHelp: 'اتركه فارغًا إذا كنت تستخدم الأسعار الثابتة فقط.',
    detailsSection: 'الأسطول وشروط العمل', detailsHelp: 'تساعدنا هذه المعلومات على مراجعة طلبك بسرعة أكبر.',
    comment: 'معلومات إضافية', commentPlaceholder: 'حجم الأسطول، فئات المركبات وسعتها، التراخيص، تصاريح المطارات، شروط الانتظار وأي معلومات مهمة أخرى.',
    submit: 'إرسال الطلب', submitting: 'جارٍ الإرسال…', consent: 'بإرسال الطلب، تسمح لـ Riderra بالتواصل معك بشأن شراكة محتملة.',
    note: 'استلمنا بياناتك وسنتواصل معك لمراجعة مناطق العمل والمركبات والأسعار.',
    error: 'تعذر إرسال الطلب. يرجى مراجعة البيانات والمحاولة مرة أخرى.'
  },
  ha: {
    eyebrow: 'Ga kamfanonin sufuri', title: 'Kasance abokin hulɗar motocin Riderra',
    lead: 'Karɓi buƙatun jigilar filin jirgi da cikin gari daga Riderra da abokan hulɗarmu. Kai ne ke zaɓar yankin aiki, motocin da farashin net.',
    startButton: 'Cika takardar nema', loginButton: 'Shigar abokin hulɗa', processTitle: 'Yadda za a fara',
    steps: [
      { title: 'Faɗa mana game da kamfaninka', text: 'Bayanan tuntuɓa da yankunan aiki.' },
      { title: 'Turo farashinka', text: 'Tsayayyun hanyoyi ko farashin kilomita.' },
      { title: 'Mu amince da sharuɗɗa', text: 'Za mu duba bayanan mu tuntube ka.' }
    ],
    applicationEyebrow: 'Neman zama abokin motocin', applicationTitle: 'Mu san juna',
    applicationText: 'Turo abin da ka sani yanzu. Za a iya ƙara fayyace farashi tare da manaja bayan an aika nema.',
    wikiButton: 'Yadda ake aiki da Riderra', alreadyRegistered: 'Ka riga ka yi rajista? Shiga',
    successEyebrow: 'An aika takardar nema', successTitle: 'Mun gode da sha’awarka ga Riderra',
    companySection: 'Kamfani da bayanan tuntuɓa', requiredNote: 'Filayen da ke da alamar tauraro wajibi ne.',
    name: 'Sunan kamfani / sunanka *', email: 'Imel na kasuwanci *', phone: 'Waya ko WhatsApp *',
    city: 'Birane da yankunan aiki *', cityHelp: 'Misali: Los Angeles, Orange County, LAX.',
    ratesSection: 'Farashin net ɗinka', ratesHelp: 'Ƙara tsayayyun hanyoyi, farashin kilomita ko duka biyun.',
    fixedRatesTitle: 'Tsayayyun hanyoyi', fixedRatesHelp: 'Farashin net na tafiya ɗaya.',
    fixedFrom: 'Daga', fixedTo: 'Zuwa', fixedPrice: 'Farashi', fixedCurrency: 'Kuɗi',
    fromPlaceholder: 'Filin jirgin LAX', toPlaceholder: 'Downtown LA', addRoute: 'Ƙara wata hanya', removeRoute: 'Cire hanya',
    routesPerKm: 'Farashi a kowace kilomita', perKmPlaceholder: 'Misali, 1.20 EUR/km', perKmHelp: 'Bar shi babu komai idan kana amfani da tsayayyun farashi kawai.',
    detailsSection: 'Motoci da sharuɗɗan aiki', detailsHelp: 'Wannan bayanin yana taimaka mana mu duba nemanka da sauri.',
    comment: 'Ƙarin bayani', commentPlaceholder: 'Adadin motoci, nau’o’i da yawan fasinjoji, lasisi, izinin filin jirgi, sharuddan jira da sauran muhimman bayanai.',
    submit: 'Aika takardar nema', submitting: 'Ana aikawa…', consent: 'Ta hanyar aikawa, ka ba Riderra izinin tuntubarka game da yiwuwar haɗin gwiwa.',
    note: 'Mun karɓi bayananka kuma za mu tuntube ka don duba yankuna, motoci da farashi.',
    error: 'Ba a iya aika takardar neman ba. Duba bayanan ka sake gwadawa.'
  }
}

export default driversCopy
